/** AdminFaculty.jsx
 * @author Anish
 * @description This is the jsx file for Admin Panel Faculty
 * @date 2-12-2025
 * @returns a JSX Layout
 */

import React, { useEffect, useState } from "react";
import {
  PlusCircle,
  Pencil,
  Trash2,
  X,
  IdCard,
  Mail,
  BookOpen,
} from "lucide-react";
import { getAccessCsrfToken } from "@/utils/csrf";

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8080";

export default function AdminFaculty() {
  const [teachers, setTeachers] = useState([]);
  const [loading, setLoading] = useState(true);

  const [modalOpen, setModalOpen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [selectedId, setSelectedId] = useState(null);

  // form fields
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // delete confirmation
  const [deleteId, setDeleteId] = useState(null);

  // last generated login_id when adding a teacher
  const [lastLoginId, setLastLoginId] = useState("");

  // subject assignment
  const [subjects, setSubjects] = useState([]);
  const [subjectsLoading, setSubjectsLoading] = useState(true);
  const [assignModalOpen, setAssignModalOpen] = useState(false);
  const [assignTeacher, setAssignTeacher] = useState(null);
  const [assignSubjectId, setAssignSubjectId] = useState("");
  const [assignBanner, setAssignBanner] = useState("");

  // -----------------------------
  // FETCH ALL TEACHERS
  // -----------------------------
  async function loadTeachers() {
    try {
      setLoading(true);
      const res = await fetch(`${API_BASE_URL}/teachers/all`, {
        credentials: "include",
      });
      const data = await res.json();
      setTeachers(data || []);
    } catch (err) {
      console.error("Failed to fetch teachers", err);
    } finally {
      setLoading(false);
    }
  }

  // -----------------------------
  // FETCH ALL SUBJECTS (FOR ASSIGNMENT)
  // -----------------------------
  async function loadSubjects() {
    try {
      setSubjectsLoading(true);
      const res = await fetch(`${API_BASE_URL}/subjects/all`, {
        credentials: "include",
      });
      const data = await res.json();
      setSubjects(data || []);
    } catch (err) {
      console.error("Failed to fetch subjects", err);
    } finally {
      setSubjectsLoading(false);
    }
  }

  useEffect(() => {
    loadTeachers();
    loadSubjects();
  }, []);

  // -----------------------------
  // OPEN ADD MODAL (REGISTER TEACHER)
  // -----------------------------
  function openAddModal() {
    setEditMode(false);
    setSelectedId(null);
    setName("");
    setEmail("");
    setPassword("");
    setModalOpen(true);
  }

  // -----------------------------
  // OPEN EDIT MODAL
  // -----------------------------
  function openEditModal(item) {
    setEditMode(true);
    setSelectedId(item.teacher_id);
    setName(item.name || "");
    setEmail(item.email || "");
    setPassword("");
    setModalOpen(true);
  }

  // -----------------------------
  // ADD / UPDATE TEACHER
  // -----------------------------
  async function handleSubmit(e) {
    e.preventDefault();

    const csrf = getAccessCsrfToken();
    const payload = {
      // login_id is auto-generated by backend when missing
      name,
      email,
      password: password || undefined,
      // NO free-text subject anymore – proper subjects via mapping only
    };

    try {
      if (editMode) {
        // UPDATE teacher
        await fetch(`${API_BASE_URL}/teachers/update/${selectedId}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            "X-CSRF-TOKEN": csrf,
          },
          credentials: "include",
          body: JSON.stringify(payload),
        });
        setLastLoginId("");
      } else {
        // ADD / REGISTER teacher
        const res = await fetch(`${API_BASE_URL}/teachers/add`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRF-TOKEN": csrf,
          },
          credentials: "include",
          body: JSON.stringify(payload),
        });

        const data = await res.json().catch(() => ({}));
        if (res.ok && data?.login_id) {
          setLastLoginId(data.login_id);
        } else {
          setLastLoginId("");
        }
      }

      setModalOpen(false);
      loadTeachers();
    } catch (err) {
      console.error("Failed to save teacher", err);
    }
  }

  // -----------------------------
  // DELETE TEACHER
  // -----------------------------
  async function confirmDelete() {
    const csrf = getAccessCsrfToken();

    try {
      await fetch(`${API_BASE_URL}/teachers/delete/${deleteId}`, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json",
          "X-CSRF-TOKEN": csrf,
        },
        credentials: "include",
      });

      setDeleteId(null);
      loadTeachers();
    } catch (err) {
      console.error("Delete failed", err);
    }
  }

  // -----------------------------
  // OPEN ASSIGN SUBJECT MODAL
  // -----------------------------
  function openAssignModal(teacher) {
    setAssignTeacher(teacher);
    setAssignSubjectId("");
    setAssignModalOpen(true);
  }

  // -----------------------------
  // ASSIGN TEACHER TO SUBJECT
  // -----------------------------
  async function handleAssignSubmit(e) {
    e.preventDefault();

    if (!assignTeacher || !assignSubjectId) {
      setAssignBanner("Please select a subject before assigning.");
      return;
    }

    const csrf = getAccessCsrfToken();

    const teacherId = Number(assignTeacher.teacher_id);
    const subjectId = Number(assignSubjectId);

    if (!teacherId || Number.isNaN(subjectId)) {
      setAssignBanner("Invalid teacher or subject id.");
      return;
    }

    try {
      const res = await fetch(`${API_BASE_URL}/subject/assign-teacher`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRF-TOKEN": csrf,
        },
        credentials: "include",
        body: JSON.stringify({
          teacher_id: teacherId,
          subject_id: subjectId,
        }),
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        console.error("Assign failed:", res.status, data);
        setAssignBanner(
          data?.error || `Failed to assign teacher (status ${res.status}).`
        );
        return;
      }

      // Find selected subject for a nicer message
      const subj = subjects.find(
        (s) => Number(s.subject_id) === subjectId
      );
      const subjLabel = subj
        ? `${subj.code || ""} ${subj.name || ""}`.trim()
        : `ID ${subjectId}`;

      setAssignBanner(
        `Assigned "${assignTeacher.name}" to subject ${subjLabel}.`
      );
    } catch (err) {
      console.error("Assign teacher failed:", err);
      setAssignBanner("Failed to assign teacher due to a network error.");
    } finally {
      setAssignModalOpen(false);
    }
  }

  // ==================================================================
  // UI
  // ==================================================================
  return (
    <div className="p-6">
      {/* PAGE HEADER */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-semibold text-grey-600">Manage Faculty</h2>

        <button
          onClick={openAddModal}
          className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r 
                     from-cyan-500 to-blue-500 hover:from-cyan-400 hover:to-blue-400 
                     px-4 py-2 text-white font-medium shadow-lg shadow-cyan-500/25 
                     hover:shadow-cyan-500/40 transition-all duration-300 hover:scale-105"
        >
          <PlusCircle className="w-5 h-5" />
          Register Faculty
        </button>
      </div>

      {/* LAST GENERATED LOGIN ID BANNER */}
      {lastLoginId && (
        <div className="mb-4 rounded-xl border border-emerald-500/80 bg-emerald-800/90 
                        px-4 py-3 text-sm text-emerald-50 flex items-center justify-between 
                        shadow-lg shadow-emerald-500/40">
          <div className="flex items-center gap-2">
            <IdCard className="w-4 h-4 text-emerald-200" />
            <span className="font-semibold">New faculty registered.</span>
            <span className="opacity-90">
              Login ID:{" "}
              <span className="ml-1 inline-flex items-center rounded-full bg-emerald-600 px-2 py-0.5 
                               font-mono text-xs font-semibold text-emerald-50 shadow-inner">
                {lastLoginId}
              </span>
            </span>
          </div>
          <button
            onClick={() => setLastLoginId("")}
            className="text-emerald-100 hover:text-white text-xs font-medium underline decoration-dotted"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* ASSIGN SUBJECT BANNER */}
      {assignBanner && (
        <div className="mb-4 rounded-xl border border-cyan-400/70 bg-cyan-900/70 
                        px-4 py-3 text-sm text-cyan-50 flex items-center justify-between 
                        shadow-lg shadow-cyan-500/40">
          <div className="flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-cyan-200" />
            <span className="font-medium">{assignBanner}</span>
          </div>
          <button
            onClick={() => setAssignBanner("")}
            className="text-cyan-100 hover:text-white text-xs font-medium underline decoration-dotted"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* TABLE */}
      <div className="bg-[#0b1220]/80 backdrop-blur-xl rounded-xl border border-white/10 shadow-2xl">
        <table className="w-full text-sm text-left text-slate-200">
          <thead className="bg-gradient-to-r from-cyan-600/30 to-blue-600/30 border-b border-white/20">
            <tr>
              <th className="px-5 py-4 font-semibold tracking-wide uppercase text-xs">
                Login ID
              </th>
              <th className="px-5 py-4 font-semibold tracking-wide uppercase text-xs">
                Name
              </th>
              <th className="px-5 py-4 font-semibold tracking-wide uppercase text-xs">
                Email
              </th>
              <th className="px-5 py-4 font-semibold tracking-wide uppercase text-xs text-right">
                Actions
              </th>
            </tr>
          </thead>

          <tbody>
            {loading && (
              <tr>
                <td
                  colSpan="4"
                  className="text-center py-6 text-slate-400 italic"
                >
                  Loading faculty...
                </td>
              </tr>
            )}

            {!loading && teachers.length === 0 && (
              <tr>
                <td
                  colSpan="4"
                  className="text-center py-6 text-slate-400 italic"
                >
                  No faculty found.
                </td>
              </tr>
            )}

            {teachers.map((item, idx) => (
              <tr
                key={item.teacher_id}
                className={`transition-all ${
                  idx % 2 === 0 ? "bg-white/5" : "bg-white/10"
                } hover:bg-cyan-500/20`}
              >
                <td className="px-5 py-4 font-mono text-[13px]">
                  {item.login_id}
                </td>
                <td className="px-5 py-4 text-[15px]">{item.name}</td>
                <td className="px-5 py-4">
                  <div className="flex items-center gap-2 max-w-xs">
                    <Mail className="w-4 h-4 text-cyan-300" />
                    <span className="truncate">{item.email}</span>
                  </div>
                </td>

                <td className="px-5 py-4">
                  <div className="flex items-center justify-end gap-4">
                    {/* ASSIGN SUBJECT */}
                    <button
                      onClick={() => openAssignModal(item)}
                      className="text-cyan-300 hover:text-cyan-200 hover:scale-110 transition-transform duration-150"
                      title="Assign to Subject"
                    >
                      <BookOpen className="w-5 h-5" />
                    </button>

                    {/* EDIT */}
                    <button
                      onClick={() => openEditModal(item)}
                      className="text-cyan-300 hover:text-cyan-400 hover:scale-110 transition-transform duration-150"
                    >
                      <Pencil className="w-5 h-5" />
                    </button>

                    {/* DELETE */}
                    <button
                      onClick={() => setDeleteId(item.teacher_id)}
                      className="text-red-400 hover:text-red-500 hover:scale-110 transition-transform duration-150"
                    >
                      <Trash2 className="w-5 h-5" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ========================================================= */}
      {/* ADD / EDIT MODAL */}
      {/* ========================================================= */}
      {modalOpen && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-[#0d1d35] border border-white/10 rounded-xl p-6 w-full max-w-lg shadow-xl relative">
            <button
              onClick={() => setModalOpen(false)}
              className="absolute top-3 right-3 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <h3 className="text-xl font-semibold text-white mb-4">
              {editMode ? "Edit Faculty" : "Register Faculty"}
            </h3>

            <form onSubmit={handleSubmit} className="space-y-4">
              {/* NAME */}
              <div>
                <label className="text-slate-300 text-sm">Name</label>
                <input
                  className="w-full mt-1 px-3 py-2 rounded-lg bg-black/20 border border-white/10 
                             focus:ring-2 focus:ring-cyan-500 text-white outline-none"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  required
                />
              </div>

              {/* EMAIL */}
              <div>
                <label className="text-slate-300 text-sm">Email</label>
                <input
                  type="email"
                  className="w-full mt-1 px-3 py-2 rounded-lg bg-black/20 border border-white/10 
                             focus:ring-2 focus:ring-cyan-500 text-white outline-none"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>

              {/* PASSWORD */}
              <div>
                <label className="text-slate-300 text-sm">
                  {editMode ? "New Password (optional)" : "Password"}
                </label>
                <input
                  type="password"
                  className="w-full mt-1 px-3 py-2 rounded-lg bg-black/20 border border-white/10 
                             focus:ring-2 focus:ring-cyan-500 text-white outline-none"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required={!editMode}
                  placeholder={editMode ? "Leave blank to keep current" : ""}
                />
              </div>

              {/* NO SUBJECT INPUT HERE ANYMORE */}

              {/* SUBMIT BUTTON */}
              <button
                type="submit"
                className="w-full rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 
                           hover:from-cyan-400 hover:to-blue-400 text-white py-2 text-lg font-medium
                           shadow-lg shadow-cyan-500/30 hover:shadow-cyan-500/50 
                           transition-all duration-300 hover:scale-[1.03]"
              >
                {editMode ? "Save Changes" : "Register Faculty"}
              </button>
            </form>
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* ASSIGN SUBJECT MODAL */}
      {/* ========================================================= */}
      {assignModalOpen && assignTeacher && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-[#0d1d35] border border-white/10 rounded-xl p-6 w-full max-w-md shadow-xl relative">
            <button
              onClick={() => setAssignModalOpen(false)}
              className="absolute top-3 right-3 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <h3 className="text-xl font-semibold text-white mb-3 flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-cyan-300" />
              Assign Subject
            </h3>
            <p className="text-slate-300 text-sm mb-4">
              Assign{" "}
              <span className="font-semibold text-white">
                {assignTeacher.name}
              </span>{" "}
              to a subject from the list below.
            </p>

            <form onSubmit={handleAssignSubmit} className="space-y-4">
              <div>
                <label className="text-slate-300 text-sm">Subject</label>
                <select
                  className="w-full mt-1 px-3 py-2 rounded-lg bg-black/20 border border-white/10 
                             focus:ring-2 focus:ring-cyan-500 text-white outline-none"
                  value={assignSubjectId}
                  onChange={(e) => setAssignSubjectId(e.target.value)}
                  required
                >
                  <option value="">Select a subject</option>
                  {subjectsLoading && (
                    <option disabled>Loading subjects...</option>
                  )}
                  {!subjectsLoading &&
                    subjects.map((s) => (
                      <option key={s.subject_id} value={s.subject_id}>
                        {s.code ? `${s.code} — ${s.name}` : s.name}
                      </option>
                    ))}
                </select>
              </div>

              <button
                type="submit"
                className="w-full rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 
                           hover:from-cyan-400 hover:to-blue-400 text-white py-2 text-lg font-medium
                           shadow-lg shadow-cyan-500/30 hover:shadow-cyan-500/50 
                           transition-all duration-300 hover:scale-[1.03]"
              >
                Assign Subject
              </button>
            </form>
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* DELETE CONFIRMATION */}
      {/* ========================================================= */}
      {deleteId && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-[#0d1d35] border border-white/10 rounded-xl p-6 w-full max-w-sm shadow-xl text-center">
            <h3 className="text-white text-lg font-semibold mb-2">
              Delete Faculty?
            </h3>
            <p className="text-slate-400 text-sm mb-4">
              This action cannot be undone.
            </p>

            <div className="flex items-center justify-center gap-3">
              <button
                onClick={() => setDeleteId(null)}
                className="px-4 py-2 rounded-lg bg-white/10 text-white hover:bg-white/20 transition"
              >
                Cancel
              </button>

              <button
                onClick={confirmDelete}
                className="px-4 py-2 rounded-lg bg-red-500/80 hover:bg-red-600 text-white transition"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
