/** utils.js
 * @author Shadcn
 * @description This file was generated by shadcn
 * @date 2/12/2025
 * @returns nothing
 */

import { clsx } from "clsx";
import { twMerge } from "tailwind-merge"

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}
